language: ruby
sudo: false
script: 'ci/travis.rb'
before_install:
  - "rvm current | grep 'jruby' && export AR_JDBC=true || echo"
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'
  matrix:
    - "GEM=railties"
    - "GEM=ap"
    - "GEM=am,amo,as,av,aj"
    - "GEM=ar:postgresql"
    - "GEM=aj:integration"
rvm:
  - 2.3
bundler_args: --without test --jobs 3 --retry 3
services:
  - memcached
  - redis
  - rabbitmq
addons:
  postgresql: "9.3"

